# Generated by Django 4.1.5 on 2023-01-15 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=500)),
                ('is_published', models.BooleanField(choices=[(True, 'Опубликовано'), (False, 'Не опубликовано')], default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='data/img')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ads.category')),
            ],
        ),
    ]
